### PR TITLE
fix style of yaml list

### PR DESCRIPTION
**Pull request by archivero-madrid**
fix style that no need to change

### CODE REVIEW

**Comment by archivero-madrid** [comment]
is this mergeable?

**Comment by archivero-madrid** [comment]
@scollazo ping

**Comment by mamedin** [comment]
Hi @archivero-madrid , I included your suggestion to the last merged PR. Can we close this PR?

Thanks for your help :)

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual-labs/ansible-percona/pull/34.

**Pull request closed without merging**
